import { useMemo, useState } from "react";

import { calculate } from "./api";
import CategoryRail from "./components/CategoryRail";
import HistoryPanel from "./components/HistoryPanel";
import PromptComposer from "./components/PromptComposer";
import ResultPanel from "./components/ResultPanel";

const CALCULATORS = [
  { id: "arithmetic", name: "Arithmetic", description: "Expressions and powers", examples: ["Calculate (18 + 6) * 4 / 3"] },
  { id: "age", name: "Age & dates", description: "Exact calendar differences", examples: ["My date of birth is 2003-08-15. Calculate my age."] },
  { id: "emi", name: "Loan EMI", description: "Payments and interest", examples: ["EMI for ₹10 lakh at 8.5% for 5 years"] },
  { id: "statistics", name: "Statistics", description: "Describe numeric datasets", examples: ["Find mean, median and standard deviation of 12, 15, 18, 21"] },
  { id: "units", name: "Unit conversion", description: "Units and dimensions", examples: ["Convert 15 kilometres to miles"] },
];

const DEFAULT_EXAMPLES = [
  "EMI for ₹10 lakh at 8.5% for 5 years",
  "Convert 15 kilometres to miles",
  "Mean of 12, 15, 18, 21",
];

function readHistory() {
  try {
    return JSON.parse(localStorage.getItem("omnicalc-history") || "[]").slice(0, 8);
  } catch {
    return [];
  }
}

export default function App() {
  const [query, setQuery] = useState("");
  const [selected, setSelected] = useState(null);
  const [result, setResult] = useState(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);
  const [history, setHistory] = useState(readHistory);

  const examples = useMemo(() => {
    const calculator = CALCULATORS.find((item) => item.id === selected);
    return calculator?.examples || DEFAULT_EXAMPLES;
  }, [selected]);

  async function handleSubmit(event) {
    event.preventDefault();
    if (!query.trim()) return;
    setLoading(true);
    setError("");
    try {
      const nextResult = await calculate(query, selected);
      setResult(nextResult);
      const nextHistory = [nextResult, ...history.filter((item) => item.query !== nextResult.query)].slice(0, 8);
      setHistory(nextHistory);
      localStorage.setItem("omnicalc-history", JSON.stringify(nextHistory));
    } catch (requestError) {
      setResult(null);
      setError(requestError.message);
    } finally {
      setLoading(false);
    }
  }

  function selectHistory(item) {
    setQuery(item.query);
    setSelected(item.calculator);
    setResult(item);
    setError("");
  }

  function clearHistory() {
    localStorage.removeItem("omnicalc-history");
    setHistory([]);
  }

  return (
    <div className="app-shell">
      <header className="topbar">
        <div className="brand-mark" aria-hidden="true"><span>∑</span></div>
        <div className="brand-copy">
          <strong>OmniCalc</strong>
          <span>AI</span>
        </div>
        <div className="topbar-status">
          <span className="status-dot" />
          Verified engine online
        </div>
      </header>

      <div className="workspace-grid">
        <CategoryRail calculators={CALCULATORS} onSelect={setSelected} selected={selected} />
        <main className="main-workspace">
          <div className="workspace-heading">
            <div>
              <span className="eyebrow">Universal calculation workspace</span>
              <h1>Describe the outcome you need.</h1>
            </div>
            <p>Numbers are computed by verified tools—not generated by the language model.</p>
          </div>
          <PromptComposer
            examples={examples}
            loading={loading}
            onQueryChange={setQuery}
            onSubmit={handleSubmit}
            query={query}
          />
          <ResultPanel error={error} loading={loading} result={result} />
        </main>
        <HistoryPanel items={history} onClear={clearHistory} onSelect={selectHistory} />
      </div>
    </div>
  );
}

